#!/bin/bash

echo WELCOME TO CIV13!
echo -----------------
echo Prepairing the system...
sudo dpkg --add-architecture i386
sudo apt update
sudo apt upgrade
sudo apt install python3 wget git unzip make sudo
sudo rm INSTALL.py
sudo wget https://raw.githubusercontent.com/slsdevs2022/Civ13-2022/master/INSTALL.py
sudo python3 INSTALL.py 514 1578